######################################################################
# generated by pvdevelop
######################################################################

TEMPLATE = app
CONFIG  += warn_on release console
CONFIG  -= qt

HEADERS += fake_qmake.h

SOURCES += main.cpp       \
           fake_qmake.cpp \
           ../rllib/lib/rlstring.cpp \
           ../rllib/lib/rlspreadsheet.cpp \
           ../rllib/lib/rlfileload.cpp \
           ../rllib/lib/rlcutil.cpp

INCLUDEPATH   += ../rllib/lib

macx:DEFINES += RLMAC
macx:DEFINES += RLUNIX

#Here Nestor: añadir la librería ws2_32 para windows
win32 {
    LIBS += -lws2_32
}

TARGET = fake_qmake
