######################################################################
# generated by pvdevelop at: Mi Nov 8 11:58:45 2006
######################################################################

TEMPLATE = app
# CONFIG  += USE_QT_SQL
CONFIG  -= qt
CONFIG  += warn_on release console
QT      += sql
DEFINES += LUA
DEFINES += "WINVER=0x0501"

# Input
SOURCES     += main.cpp                                   \       
               ../../language_binding_rllib_wrap_lua.cxx  \
               ../../language_binding_wrap_lua.cxx        \
               ../../pvmain.cpp
USE_QT_SQL {
DEFINES += USE_QT_SQL
CONFIG  += qt
SOURCES +=../../sql/qtdatabase.cpp                   
}

INCLUDEPATH += ../lua-5.4.0/src/

!macx { #Nestor aquí
    unix:LIBS          += -L$$PWD/../lua-5.4.0/src -llua
    unix:LIBS          += -L$$PWD/../../../pvserver -lpvsmt -lpthread
    unix:INCLUDEPATH   += $$PWD/../../../pvserver

    unix:LIBS          += -L$$PWD/../../../rllib/lib -lrllib
    unix:INCLUDEPATH   += $$PWD/../../../rllib/lib

    unix:LIBS          += -ldl
}

macx:LIBS          += ../../../pvserver/libpvsmt.a /usr/lib/libpthread.dylib
macx:INCLUDEPATH   += ../../../pvserver
macx:LIBS          += ../../../rllib/lib/librllib.dylib
macx:INCLUDEPATH   += ../../../rllib/lib

win32-g++ {
QMAKE_LFLAGS       += -static-libgcc
win32:LIBS += $$PWD/../lua-5.4.0/src/liblua.a
win32:LIBS += $$PWD/../../../rllib/lib/librllib.a
win32:LIBS += $$PWD/../../../pvserver/libserverlib.a -lws2_32 -ladvapi32
win32:INCLUDEPATH  += $$PWD/../../../rllib/lib
win32:INCLUDEPATH  += $$PWD/../../../pvserver
}

#DEFINES += USE_INETD
TARGET = pvapplua
